/**
 * 错误码枚举
 * 统一的错误码定义，便于错误处理和国际化
 */
export enum ErrorCodes {
  // 认证错误（AUTH_XXX）
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS', // 无效凭据
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND', // 用户不存在
  AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS', // 用户已存在
  AUTH_USER_NOT_AUTHORIZED = 'AUTH_USER_NOT_AUTHORIZED', // 用户未授权
  AUTH_USER_NOT_AUTHENTICATED = 'AUTH_USER_NOT_AUTHENTICATED', // 用户未认证
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED', // 令牌已过期

  // 用户错误（USER_XXX）
  USER_NOT_FOUND = 'USER_NOT_FOUND', // 用户不存在
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS', // 用户已存在
  USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED', // 用户未授权
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED', // 用户未认证

  // 系统错误（SYSTEM_XXX）
  SYSTEM_ERROR = 'SYSTEM_ERROR', // 系统错误
  SYSTEM_UNAVAILABLE = 'SYSTEM_UNAVAILABLE', // 系统不可用
  SYSTEM_TIMEOUT = 'SYSTEM_TIMEOUT', // 系统超时

  // 数据库错误（DATABASE_XXX）
  DATABASE_ERROR = 'DATABASE_ERROR', // 数据库错误
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR', // 数据库连接错误
  DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR', // 数据库查询错误
  DATABASE_TRANSACTION_ERROR = 'DATABASE_TRANSACTION_ERROR', // 数据库事务错误
  DATABASE_TRANSACTION_ROLLBACK_ERROR = 'DATABASE_TRANSACTION_ROLLBACK_ERROR', // 事务回滚错误
  DATABASE_TRANSACTION_COMMIT_ERROR = 'DATABASE_TRANSACTION_COMMIT_ERROR', // 事务提交错误

  // 验证错误（VALIDATION_XXX）
  VALIDATION_ERROR = 'VALIDATION_ERROR', // 验证错误
  VALIDATION_FAILED = 'VALIDATION_FAILED', // 验证失败
  VALIDATION_REQUIRED = 'VALIDATION_REQUIRED', // 必填字段
  VALIDATION_INVALID = 'VALIDATION_INVALID', // 无效值
  VALIDATION_UNIQUE = 'VALIDATION_UNIQUE', // 唯一性验证
  VALIDATION_MIN_LENGTH = 'VALIDATION_MIN_LENGTH', // 最小长度
  VALIDATION_MAX_LENGTH = 'VALIDATION_MAX_LENGTH', // 最大长度
  VALIDATION_PATTERN = 'VALIDATION_PATTERN', // 格式验证
  VALIDATION_MIN = 'VALIDATION_MIN', // 最小值
  VALIDATION_MAX = 'VALIDATION_MAX', // 最大值
}
